AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  MyFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs8.10
      Description: Collect logs from S3, preprocess and route them with Cribl
      MemorySize: 512
      Timeout: 10
      CodeUri: 's3://cdn.cribl.io/repo/S3ToCribl.zip'
      Environment:
        Variables:
          CRIBL_URL: <enter value here>
          CRIBL_AUTH: <enter value here>
