AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  S3LogsToCribl:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs8.10
      Description: Collect logs from S3, preprocess and route them with Cribl
      MemorySize: 512
      Timeout: 20
      CodeUri: 's3://cdn.cribl.io/aws/serverless/S3LogsToCribl.zip'
      Environment:
        Variables:
          CRIBL_URL: < Cribl HTTP input endpoint >
          CRIBL_AUTH: < Cribl HTTP authToken >
